# Generated by Django 4.0.3 on 2022-03-26 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KidTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('parent_phone', models.IntegerField()),
                ('parent_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ImageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='MEDIA_ROOT/uploads/%Y/%m/%d/')),
                ('image_url', models.URLField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('is_approved', models.BooleanField()),
                ('approved_by', models.CharField(max_length=100)),
                ('food_group', models.CharField(choices=[('Fruit', 'Fruit'), ('Veg', 'Vegetable'), ('Grain', 'Grain'), ('Protein', 'Protein'), ('Dairy', 'Dairy'), ('Unknown', 'Unknown')], max_length=100)),
                ('kidtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kid.kidtable')),
            ],
        ),
    ]
