# Generated by Django 4.0.3 on 2022-03-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagetable',
            old_name='kidtable',
            new_name='kid_table',
        ),
    ]
